// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okvplkwsrncxtxhhgtct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rdnBsa3dzcm5jeHR4aGhndGN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NjM5NzAsImV4cCI6MjA3MjAzOTk3MH0.bTzhChSA8__ayOIgq12vpguWz0Gvr3Q1erw6dwkqJg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});